# Created using wingetcreate 1.5.5.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.5.0.schema.json

PackageIdentifier: Microsoft.err
PackageVersion: 6.4.5
PackageLocale: en-US
Publisher: Microsoft Corporation
PackageName: Error Lookup Tool
License: Proprietary
Copyright: Copyright (c) Microsoft Corporation.
ShortDescription: The Error Lookup Tool, also known as "ERR", is a command-line tool to decode many Microsoft error codes. It does not require elevation and is very easy to use.
ManifestType: defaultLocale
ManifestVersion: 1.5.0
